# Copyright 2018 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

version: 1
definitions:
  defaults:
    # Run default content from github repo
    - &productionRepo https://github.com/adobe/developer.adobe.com.git#master
    - &devRepo https://github.com/adobe/developer.adobe.com.git#REPLACED_BY_CI
  strains:
    base:
      &productionDefaults
      code: *productionRepo
      content: *productionRepo
      static: *productionRepo
    dev:
      &devDefaults
      code: *devRepo
      content: *devRepo
      static: *devRepo
    proxy:
      &proxyToAdobeIO
      origin: https://www.adobe.io/

strains:
  - name: default
    <<: *productionDefaults
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b

  # === DEV ENVIRONMENT URLS FOLLOW ===
  - name: launch-docs-dev
    <<: *devDefaults
    url: https://adobedevsite.helix-demo.xyz/launch/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/7c34f33b5047a8f7ad5847148c49303c8e10514f
  - name: xd-docs-dev
    <<: *devDefaults
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/7c34f33b5047a8f7ad5847148c49303c8e10514f
  - name: starter-docs-dev
    <<: *devDefaults
    url: https://adobedevsite.helix-demo.xyz/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#author
    directoryIndex: Overview.html
    package: developer-adobe-com/7c34f33b5047a8f7ad5847148c49303c8e10514f
  - name: support-dev
    origin: https://adobedocs.github.io/developer-support/
    url: https://adobedevsite.helix-demo.xyz/support
  - name: static-dev
    <<: *devDefaults
    url: https://adobedevsite.helix-demo.xyz/static/
    package: developer-adobe-com/7c34f33b5047a8f7ad5847148c49303c8e10514f
  - name: dev
    <<: *proxyToAdobeIO
    url: https://adobedevsite.helix-demo.xyz/

  # === STAGING ENVIRONMENT URLS FOLLOW ===
  - name: launch-docs-staging
    <<: *productionDefaults
    url: https://adobedevsite.helix-demo.xyz/launch/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: xd-docs-staging
    <<: *productionDefaults
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: starter-docs-staging
    <<: *productionDefaults
    url: https://adobedevsite.helix-demo.xyz/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#author
    directoryIndex: Overview.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: support-staging
    origin: https://adobedocs.github.io/developer-support/
    url: https://adobedevsite.helix-demo.xyz/support
  - name: static-staging
    <<: *productionDefaults
    url: https://adobedevsite.helix-demo.xyz/static/
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: staging
    <<: *proxyToAdobeIO
    url: https://adobedevsite.helix-demo.xyz/

  # === PRODUCTION ENVIRONMENT URLS FOLLOW ===
  - name: launch-docs-production
    <<: *productionDefaults
    url: https://developer.adobe.com/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: xd-docs-production
    <<: *productionDefaults
    url: https://developer.adobe.com/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: starter-docs-production
    <<: *productionDefaults
    url: https://developer.adobe.com/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#master
    directoryIndex: Overview.html
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: support-production
    origin: https://adobedocs.github.io/developer-support/
    url: https://developer.adobe.com/support
  - name: static-production
    <<: *productionDefaults
    url: https://developer.adobe.com/static/
    package: developer-adobe-com/8e402f27d9acac2a02d135d22a14db9ead5c280b
  - name: production
    <<: *proxyToAdobeIO
    url: https://developer.adobe.com/
