# Copyright 2018 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

version: 1
definitions:
  defaults:
    # Run default content from github repo
    - &defaultRepo https://github.com/adobe/developer.adobe.com.git#master
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
    proxy:
      &proxystrain
      origin: https://www.adobe.io/

strains:
  - name: default
    <<: *basestrain
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e

  # === STAGING URLS FOLLOW ===
  - name: launch-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/launch/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: xd-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    # TODO: the following repo has no author or staging branch
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: starter-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#author
    directoryIndex: Overview.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: support-staging
    origin: https://adobedocs.github.io/developer-support/
    url: https://adobedevsite.helix-demo.xyz/support
  - name: static-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/static/
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: staging
    <<: *proxystrain
    url: https://adobedevsite.helix-demo.xyz/

  # === PRODUCTION URLS FOLLOW ===
  - name: launch-docs-production
    <<: *basestrain
    url: https://developer.adobe.com/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: xd-docs-production
    <<: *basestrain
    url: https://developer.adobe.com/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: starter-docs-production
    <<: *basestrain
    url: https://developer.adobe.com/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#master
    directoryIndex: Overview.html
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: support-production
    origin: https://adobedocs.github.io/developer-support/
    url: https://developer.adobe.com/support
  - name: static-production
    <<: *basestrain
    url: https://developer.adobe.com/static/
    package: developer-adobe-com/2eb6ea9ff22d55af50ed0f8515e730e3be4e7a1e
  - name: production
    <<: *proxystrain
    url: https://developer.adobe.com/
